#!/usr/bin/env python

#Example publish rostopic pub /user_input std_msgs/String "1.0,2.0,3.0"

import rospy
from geometry_msgs.msg import PoseStamped
from std_msgs.msg import String

def user_input_callback(data):
    try:
        # Parse user input string and extract x, y, z values
        x, y, z = map(float, data.data.split(','))

        # Create a PoseStamped message for the arm goal
        arm_goal = PoseStamped()
        arm_goal.header.stamp = rospy.Time.now()
        arm_goal.pose.position.x = x
        arm_goal.pose.position.y = y
        arm_goal.pose.position.z = z
        arm_goal.pose.orientation.x = 0.0
        arm_goal.pose.orientation.y = -1.0
        arm_goal.pose.orientation.z = 0.0
        arm_goal.pose.orientation.w = 0.0

        # Publish the arm goal
        arm_goal_publisher.publish(arm_goal)

    except ValueError:
        rospy.logerr("Invalid input format. Please provide x, y, z values separated by commas.")

if __name__ == '__main__':
    rospy.init_node('user_input_node', anonymous=True)

    # Create a publisher for the "arm_goal" topic
    arm_goal_publisher = rospy.Publisher('arm_goal', PoseStamped, queue_size=10)

    # Create a subscriber for user input
    rospy.Subscriber('user_input', String, user_input_callback)

    rospy.spin()
